---
# list of applications to install
general:
  local_home: "{{ lookup('env','HOME') }}"

# homebrew applications
applications:
  - ag
  - coreutils
  - ctags
  - curl
  - docker
  - docker-compose
  - docker-machine
  - docker-machine-parallels
  - dos2unix
  - findutils
  - gawk
  - git
  - gnu-getopt
  - gnu-indent
  - gnu-sed
  - gnu-tar
  - gnupg
  - gnutls
  - go
  - google-java-format
  - grep
  - highlight
  - htop
  - httpie
  - jsonpp
  - kubectl
  - kubernetes-helm
  - less
  - mosh
  - multitail
  - neovim
  - nmap
  - npm                                # Node.js Package Manager
  - nodeenv                            # Virtualenv for Node.js
  - openssh
  - packer
  - postgres
  - python3
  - readline
  - rsync
  - ruby
  - sbt
  - scalariform
  - tmux
  - tree
  - typesafe-activator
  - uni2ascii
  - telnet
  - vim
  - wakeonlan
  - watch
  - watchman                           # Needed for node tests or something
  - wget
#  - autojump
#  - hugo
#  - saltstack
#  - terraform
#  - zsh

# homebrew cask applications
cask_applications:
  - 1password
  - adobe-acrobat-reader
  - alfred
  - bettertouchtool
  - caffeine
  - dash
  - disk-inventory-x
  - dropbox
  - firefox
  - google-chrome
  - haptic-touch-bar                   # Provides physical feedback for Apple's Touch Bar
  - insomnia                           # HTTP request generator
  - intellij-idea-ce
  - istat-menus
  - iterm2
  - java
  - kitematic                          # GUI for Docker containers
  - macvim
  - magicprefs
  - minikube
  - opera
  - parallels
  - postico
  - skype
  - slack
  - soundcleod
  - spotify
  - steam
  - telegram
  - torbrowser
  - transmission
  - tunnelbear
  - tunnelblick
  - vagrant
  - viber
  - vlc
  - whatsapp
