---
# install and update homebrew and cask

- name: Ensure Homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes
    upgrade_all: yes

#- name: tap homebrew caskroom/cask
#  homebrew_tap:
#    tap: "caskroom/cask"
#    state: present

- name: Ensure Homebrew cask is updated
  homebrew_cask:
    state: latest
    update_homebrew: yes
    upgrade_all: yes
    greedy: yes
