---
# install and update homebrew and cask

- name: ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes
    upgrade_all: yes

- name: tap homebrew caskroom/cask
  homebrew_tap:
    tap: "caskroom/cask"

- name: tap homebrew neovim/homebrew-neovim
  homebrew_tap:
    tap: "neovim/homebrew-neovim"
    state: present
